#! /usr/bin/env node

var resolve = require('resolve');
try {
  var localButler = resolve.sync('butler', { basedir: process.cwd() });
  console.log('Found butler at', localButler);
  // kick off here
} catch (e) {
  console.log('Unable to find a local installation of butler.');
  process.exit(1);
}