# Site configuration

title: 'STYLEGUIDE TEMPLATE'
url: ''

server_watch_ext: ['html', 'htm', 'xml', 'css', 'js', 'twig', 'md']

collections:
  elements:
    output: true
    title: "Elements"
    sort_by: title
    sort_type: 'ascending'

  components:
    output: true
    title: "Components"
    sort_by: title
    sort_type: 'ascending'

  comps:
    output: true
    title: "High Fidelity Comps"
    sort_by: title
    sort_type: 'ascending'